@RailWaysideMonitor_HostAddress = http://localhost:5107

GET {{RailWaysideMonitor_HostAddress}}/api/devices
Accept: application/json

###

GET {{RailWaysideMonitor_HostAddress}}/api/events
Accept: application/json

###

GET {{RailWaysideMonitor_HostAddress}}/api/alerts
Accept: application/application/json

###

POST {{RailWaysideMonitor_HostAddress}}/api/events
Content-Type: application/json

{
    "deviceId": "TRACK-A",
    "newState": "Occupied",
    "timestamp": "2026-09-08T22:45:00"
}

###

POST {{RailWaysideMonitor_HostAddress}}/api/events
Content-Type: application/json

{
    "deviceId": "TRACK-A",
    "newState": "Warning",
    "timestamp": "2026-09-08T22:45:00"
}

###

POST {{RailWaysideMonitor_HostAddress}}/api/events
Content-Type: application/json

{
    "deviceId": "SIGNAL-A",
    "newState": "Occupied",
    "timestamp": "2026-09-08T22:45:00"
}

###

POST {{RailWaysideMonitor_HostAddress}}/api/events
Content-Type: application/json

{
    "deviceId": "DNE",
    "newState": "Occupied",
    "timestamp": "2026-09-08T22:45:00"
}

###

POST {{RailWaysideMonitor_HostAddress}}/api/events
Content-Type: application/json

{
    "deviceId": "TRACK-A",
    "newState": "DNE",
    "timestamp": "2026-09-08T22:45:00"
}

###
